#!/usr/bin/env bash
# Start the mas server for testing.
# vi: expandtab


mas_running() {
    if [ $# == 0 ]; then return 255; fi
    p=$1
    if pgrep $pgrep_opts "mas *-b.*$p" >/dev/null; then
        return 0
    else
        return 1
    fi
}

start_mas_server() {
    if [ $# == 0 ]; then return 255; fi
    p=$1
    $exe -b -f , $p *.txt&
}

if [ -z "$TATDEV" ]; then
    echo "Error: TATDEV env. var. not set" >&2
    exit 42
fi
cd $TATDEV/library/test/masdev || {
    echo "Could not cd to MAS dev/run directory - aborting ..." >&2
    exit 43
}
script_path=$(dirname $0)
pgrep_opts='-laf'
if lsb_release -a 2>/dev/null|egrep -qi 'ubuntu'; then
    pgrep_opts='-lf'
fi
cd $script_path >/dev/null
ports=$(for p in 5441 5442 5443 5444; do echo $p;done|sort -u)
exe=mas
if [ $# -gt 0 ]; then
    case $1 in
        -a|assert) exe=masx_assert
    esac
fi

all_mas_procs_were_running=true
for p in $ports; do
    if mas_running $p; then
        :
    else
        start_mas_server $p
        all_mas_procs_were_running=false
    fi
done
if ! eval "$all_mas_procs_were_running"; then
    sleep 1 # Give the server a chance to start-up/initialize.
fi
