#!/usr/bin/env bash
# Start the mas server for testing.
# vi: expandtab

script_path=$(dirname $0)
pgrep_opts='-laf'
if lsb_release -a 2>/dev/null|egrep -qi 'ubuntu'; then
    pgrep_opts='-lf'
fi
cd $script_path >/dev/null
if [ -z "$MASPORT" ]; then
    . ./.env
fi
ports=$(for p in $MASPORT 5441 5442 5443 5444; do echo $p;done|sort -u)
exe=mas
if [ $# -gt 0 ]; then
    case $1 in
        -a|assert) exe=masx_assert
    esac
fi

# Exit if mas is already running.
if pgrep $pgrep_opts "mas *-b.*$MASPORT" >/dev/null; then exit 0; fi
if pgrep $pgrep_opts "masx.*-b.*$MASPORT" >/dev/null; then exit 0; fi
if pgrep $pgrep_opts "oldmas *-b.*$MASPORT" >/dev/null; then exit 0; fi
$exe -b -w -f , $ports&
sleep 1 # Give the server a chance to start-up/initialize.
