#!/usr/bin/env ruby

def config_paths
  dirs = %w(client_library/support client_server/ma_server_protocols
    client_server/shared_protocols clients/macl/root clients/macl/support
    eiffel_library/architectural eiffel_library/debug eiffel_library/server
    eiffel_library/support
  )

  if File.symlink?($0) then
    base_path = "#{File.dirname(File.readlink($0))}/../../.."
  else
    base_path = "#{File.dirname($0)}/../../.."
  end
  dirs.each do |d|
    $LOAD_PATH << "#{base_path}/#{d}"
  end
end

config_paths

require 'object_extension'
require 'macl'

m = Macl.new
